In [1]:
#Import pandas and numpy for data processing
import pandas as pd
import numpy as np

#Import sklearn libraries and packages for test/train data split
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split

In [2]:
#Read data
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
#Check data points for data
concrete_data.shape

(1030, 9)

In [4]:
#Describe dataset
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
#Check for missing data
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
#Split the datasets into training and test

X_train, X_test = train_test_split(concrete_data, test_size=0.3)

In [7]:
#Break Dataset into predictors and targets for training and test datasets
concrete_data_columns_train = X_train.columns
concrete_data_columns_test = X_test.columns

predictors_train = X_train[concrete_data_columns_train[concrete_data_columns_train != 'Strength']]
target_train = X_train['Strength'] 

predictors_test = X_test[concrete_data_columns_test[concrete_data_columns_test != 'Strength']]
target_test = X_test['Strength']

In [8]:
#Check predictors dataset
predictors_train.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
640,400.0,0.0,0.0,187.0,0.0,1025.0,745.0,7
611,277.0,0.0,0.0,191.0,0.0,968.0,856.0,14
779,295.0,0.0,0.0,185.0,0.0,1069.0,769.0,28
603,339.0,0.0,0.0,197.0,0.0,968.0,781.0,180
580,290.2,193.5,0.0,185.7,0.0,998.2,704.3,7

In [9]:
#Check target dataset
target_train.head()

640    30.14
611    21.26
779    25.18
603    36.45
580    21.86
Name: Strength, dtype: float64

In [10]:
#Normalize data to improve training efficiency
predictors_train_norm = (predictors_train - predictors_train.mean()) / predictors_train.std()
predictors_test_norm = (predictors_test - predictors_test.mean()) / predictors_test.std()
#predictors_norm.head()

predictors_train = predictors_train_norm
predictors_test = predictors_test_norm

In [11]:
#Saving the columns as n_cols
#n_cols = predictors_norm.shape[1] # number of predictors
n_cols_train = predictors_train.shape[1]
n_cols_test = predictors_test.shape[1]

In [12]:
#Baseline model code starts here
#Import all the necessary libraries and packages
import keras

from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [13]:
# define regression model
import keras.backend as K

def mean_pred(predictors_test, target_test):
    return K.mean(target_test)

def std_pred(predictors_test, target_test):
    return K.std(target_test)

def regression_model():
    # create model - 10 nodes, relu activation function, 'adam' optimizer and 'mean_squared_error'
    #Note - data is not normalized
    model_train = Sequential()
    model_train.add(Dense(10, activation='relu', input_shape=(n_cols_train,)))
    model_train.add(Dense(10, activation='relu'))
    model_train.add(Dense(1))
    
    # compile model
    model_train.compile(optimizer='adam', loss='mean_squared_error',  metrics=[mean_pred, std_pred] )
    return model_train

In [14]:
# build the model
model_train = regression_model()

In [15]:
# fit the model - Requested 50 epochs - against test data with the mean, std and the mean squared error
#model_train.fit(predictors_train, target_train, validation_split=0.3, epochs=50, verbose=2)

model_train.fit(predictors_train, target_train, validation_data=(predictors_test,target_test), epochs=50, verbose=2)

Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 1s - loss: 1540.3301 - mean_pred: 0.0974 - std_pred: 0.2388 - val_loss: 1569.0250 - val_mean_pred: 0.2066 - val_std_pred: 0.2690
Epoch 2/50
 - 0s - loss: 1522.6692 - mean_pred: 0.3223 - std_pred: 0.3352 - val_loss: 1551.1536 - val_mean_pred: 0.4349 - val_std_pred: 0.3633
Epoch 3/50
 - 0s - loss: 1503.5809 - mean_pred: 0.5664 - std_pred: 0.4608 - val_loss: 1530.8152 - val_mean_pred: 0.6954 - val_std_pred: 0.4836
Epoch 4/50
 - 0s - loss: 1481.5741 - mean_pred: 0.8484 - std_pred: 0.6097 - val_loss: 1506.2504 - val_mean_pred: 1.0118 - val_std_pred: 0.6367
Epoch 5/50
 - 0s - loss: 1453.9711 - mean_pred: 1.2046 - std_pred: 0.8136 - val_loss: 1476.5020 - val_mean_pred: 1.4005 - val_std_pred: 0.8198
Epoch 6/50
 - 0s - loss: 1420.1984 - mean_pred: 1.6522 - std_pred: 1.0473 - val_loss: 1437.1872 - val_mean_pred: 1.9185 - val_std_pred: 1.0703
Epoch 7/50
 - 0s - loss: 1375.7685 - mean_pred: 2.2451 - std_pred: 1.3985 - val_loss: 1387.0532 - val_mean_pred: 2.5955 - val_std_pred: 1.4011
Epoch 8/50
 - 0s - loss: 1318.9270 - mean_pred: 3.0210 - std_pred: 1.8050 - val_loss: 1324.9547 - val_mean_pred: 3.4559 - val_std_pred: 1.8049
Epoch 9/50
 - 0s - loss: 1250.3039 - mean_pred: 3.9935 - std_pred: 2.3091 - val_loss: 1248.3170 - val_mean_pred: 4.5540 - val_std_pred: 2.3112
Epoch 10/50
 - 0s - loss: 1167.1713 - mean_pred: 5.2138 - std_pred: 2.9267 - val_loss: 1157.7950 - val_mean_pred: 5.9082 - val_std_pred: 2.9089
Epoch 11/50
 - 0s - loss: 1070.0687 - mean_pred: 6.7224 - std_pred: 3.6994 - val_loss: 1053.8288 - val_mean_pred: 7.5442 - val_std_pred: 3.6004
Epoch 12/50
 - 0s - loss: 961.1320 - mean_pred: 8.5300 - std_pred: 4.5782 - val_loss: 939.5295 - val_mean_pred: 9.4707 - val_std_pred: 4.3764
Epoch 13/50
 - 0s - loss: 844.9758 - mean_pred: 10.6185 - std_pred: 5.5079 - val_loss: 818.7161 - val_mean_pred: 11.6749 - val_std_pred: 5.2502
Epoch 14/50
 - 0s - loss: 727.1173 - mean_pred: 12.9888 - std_pred: 6.5303 - val_loss: 697.8962 - val_mean_pred: 14.1115 - val_std_pred: 6.1861
Epoch 15/50
 - 0s - loss: 613.6427 - mean_pred: 15.5188 - std_pred: 7.6069 - val_loss: 584.9326 - val_mean_pred: 16.6709 - val_std_pred: 7.1335
Epoch 16/50
 - 0s - loss: 511.4714 - mean_pred: 18.2013 - std_pred: 8.6895 - val_loss: 482.8859 - val_mean_pred: 19.3390 - val_std_pred: 8.1031
Epoch 17/50
 - 0s - loss: 422.6138 - mean_pred: 20.8342 - std_pred: 9.7334 - val_loss: 400.7841 - val_mean_pred: 21.8753 - val_std_pred: 8.9561
Epoch 18/50
 - 0s - loss: 354.1182 - mean_pred: 23.3811 - std_pred: 10.4373 - val_loss: 334.2434 - val_mean_pred: 24.3320 - val_std_pred: 9.8036
Epoch 19/50
 - 0s - loss: 301.4399 - mean_pred: 25.7286 - std_pred: 11.3011 - val_loss: 286.7746 - val_mean_pred: 26.4813 - val_std_pred: 10.5103
Epoch 20/50
 - 0s - loss: 266.0082 - mean_pred: 27.8178 - std_pred: 12.1749 - val_loss: 252.6540 - val_mean_pred: 28.4029 - val_std_pred: 11.1059
Epoch 21/50
 - 0s - loss: 242.0870 - mean_pred: 29.5688 - std_pred: 12.6932 - val_loss: 230.9379 - val_mean_pred: 29.9195 - val_std_pred: 11.5568
Epoch 22/50
 - 0s - loss: 227.2211 - mean_pred: 30.8568 - std_pred: 12.9329 - val_loss: 218.2744 - val_mean_pred: 30.9845 - val_std_pred: 11.7904
Epoch 23/50
 - 0s - loss: 217.4469 - mean_pred: 31.8590 - std_pred: 12.9658 - val_loss: 209.0869 - val_mean_pred: 31.8949 - val_std_pred: 11.9861
Epoch 24/50
 - 0s - loss: 210.7574 - mean_pred: 32.5682 - std_pred: 13.0199 - val_loss: 203.2123 - val_mean_pred: 32.4642 - val_std_pred: 12.0588
Epoch 25/50
 - 0s - loss: 205.6906 - mean_pred: 33.1232 - std_pred: 13.0288 - val_loss: 199.0835 - val_mean_pred: 32.8984 - val_std_pred: 12.0933
Epoch 26/50
 - 0s - loss: 201.5802 - mean_pred: 33.4656 - std_pred: 13.0850 - val_loss: 195.7416 - val_mean_pred: 33.1760 - val_std_pred: 12.0976
Epoch 27/50
 - 0s - loss: 198.1126 - mean_pred: 33.6686 - std_pred: 12.9335 - val_loss: 193.1022 - val_mean_pred: 33.3805 - val_std_pred: 12.0963
Epoch 28/50
 - 0s - loss: 194.8465 - mean_pred: 33.7881 - std_pred: 13.0185 - val_loss: 190.6128 - val_mean_pred: 33.4915 - val_std_pred: 12.0165
Epoch 29/50
 - 0s - loss: 192.1569 - mean_pred: 34.0281 - std_pred: 12.7483 - val_loss: 188.2489 - val_mean_pred: 33.7225 - val_std_pred: 12.0154
Epoch 30/50
 - 0s - loss: 189.4121 - mean_pred: 34.2220 - std_pred: 12.8651 - val_loss: 185.7994 - val_mean_pred: 33.8504 - val_std_pred: 12.0517
Epoch 31/50
 - 0s - loss: 187.1700 - mean_pred: 34.3465 - std_pred: 12.8121 - val_loss: 183.6522 - val_mean_pred: 33.9676 - val_std_pred: 12.0850
Epoch 32/50
 - 0s - loss: 184.8057 - mean_pred: 34.2899 - std_pred: 12.8174 - val_loss: 182.2158 - val_mean_pred: 33.9320 - val_std_pred: 11.9659
Epoch 33/50
 - 0s - loss: 182.2784 - mean_pred: 34.3648 - std_pred: 12.8416 - val_loss: 180.0414 - val_mean_pred: 34.0725 - val_std_pred: 12.0436
Epoch 34/50
 - 0s - loss: 180.1706 - mean_pred: 34.4896 - std_pred: 12.8527 - val_loss: 178.0311 - val_mean_pred: 34.1266 - val_std_pred: 12.0569
Epoch 35/50
 - 0s - loss: 178.1578 - mean_pred: 34.4437 - std_pred: 12.6436 - val_loss: 176.4219 - val_mean_pred: 34.0905 - val_std_pred: 12.0068
Epoch 36/50
 - 0s - loss: 176.2325 - mean_pred: 34.6419 - std_pred: 12.6948 - val_loss: 174.1451 - val_mean_pred: 34.3412 - val_std_pred: 12.1035
Epoch 37/50
 - 0s - loss: 173.8831 - mean_pred: 34.6397 - std_pred: 12.7523 - val_loss: 172.7034 - val_mean_pred: 34.2461 - val_std_pred: 12.0221
Epoch 38/50
 - 0s - loss: 172.1745 - mean_pred: 34.5387 - std_pred: 12.4971 - val_loss: 171.2339 - val_mean_pred: 34.1862 - val_std_pred: 11.9682
Epoch 39/50
 - 0s - loss: 170.1860 - mean_pred: 34.5948 - std_pred: 12.6671 - val_loss: 169.1010 - val_mean_pred: 34.3110 - val_std_pred: 12.0333
Epoch 40/50
 - 0s - loss: 168.2693 - mean_pred: 34.5933 - std_pred: 12.5770 - val_loss: 167.9102 - val_mean_pred: 34.2732 - val_std_pred: 12.0017
Epoch 41/50
 - 0s - loss: 166.4219 - mean_pred: 34.6686 - std_pred: 12.6006 - val_loss: 165.7632 - val_mean_pred: 34.4057 - val_std_pred: 12.0786
Epoch 42/50
 - 0s - loss: 164.5537 - mean_pred: 34.7251 - std_pred: 12.6190 - val_loss: 164.4283 - val_mean_pred: 34.3947 - val_std_pred: 12.0775
Epoch 43/50
 - 0s - loss: 162.8077 - mean_pred: 34.8120 - std_pred: 12.8097 - val_loss: 162.2600 - val_mean_pred: 34.5441 - val_std_pred: 12.1593
Epoch 44/50
 - 0s - loss: 161.0021 - mean_pred: 34.8028 - std_pred: 12.7188 - val_loss: 160.9222 - val_mean_pred: 34.4754 - val_std_pred: 12.1380
Epoch 45/50
 - 0s - loss: 159.5287 - mean_pred: 34.8120 - std_pred: 12.5606 - val_loss: 159.5292 - val_mean_pred: 34.5445 - val_std_pred: 12.1710
Epoch 46/50
 - 0s - loss: 157.9874 - mean_pred: 34.7675 - std_pred: 12.6524 - val_loss: 158.7660 - val_mean_pred: 34.4543 - val_std_pred: 12.1030
Epoch 47/50
 - 0s - loss: 156.5351 - mean_pred: 34.8167 - std_pred: 12.5609 - val_loss: 157.1833 - val_mean_pred: 34.5887 - val_std_pred: 12.1245
Epoch 48/50
 - 0s - loss: 155.1043 - mean_pred: 34.9291 - std_pred: 12.4912 - val_loss: 155.5768 - val_mean_pred: 34.6687 - val_std_pred: 12.1835
Epoch 49/50
 - 0s - loss: 153.9403 - mean_pred: 35.0096 - std_pred: 12.6454 - val_loss: 154.3277 - val_mean_pred: 34.8006 - val_std_pred: 12.2665
Epoch 50/50
 - 0s - loss: 152.3906 - mean_pred: 34.9250 - std_pred: 12.6218 - val_loss: 153.4902 - val_mean_pred: 34.6332 - val_std_pred: 12.1798

In [ ]:
## the mean of the normalized data is much lower than the mean of the un-normalized dataset