In [1]:
#Import pandas and numpy for data processing
import pandas as pd
import numpy as np

#Import sklearn libraries and packages for test/train data split
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split

In [2]:
#Read data
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
#Check data points for data
concrete_data.shape

(1030, 9)

In [4]:
#Describe dataset
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
#Check for missing data
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
#Split the datasets into training and test

X_train, X_test = train_test_split(concrete_data, test_size=0.3)

In [7]:
#Break Dataset into predictors and targets for training and test datasets
concrete_data_columns_train = X_train.columns
concrete_data_columns_test = X_test.columns

predictors_train = X_train[concrete_data_columns_train[concrete_data_columns_train != 'Strength']]
target_train = X_train['Strength'] 

predictors_test = X_test[concrete_data_columns_test[concrete_data_columns_test != 'Strength']]
target_test = X_test['Strength']

In [8]:
#Check predictors dataset
predictors_train.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
774,382.0,0.0,0.0,186.0,0.0,1111.0,784.0,7
781,296.0,0.0,0.0,192.0,0.0,1085.0,765.0,7
153,323.7,282.8,0.0,183.8,10.3,942.7,659.9,56
943,151.6,0.0,111.9,184.4,7.9,992.0,815.9,28
501,491.0,26.0,123.0,210.0,3.9,882.0,699.0,3

In [9]:
#Check target dataset
target_train.head()

774    11.47
781    14.20
153    80.20
943    12.18
501    25.61
Name: Strength, dtype: float64

In [10]:
#Normalize data to improve training efficiency
#predictors_norm = (predictors - predictors.mean()) / predictors.std()
#predictors_norm.head()

In [11]:
#Saving the columns as n_cols
#n_cols = predictors_norm.shape[1] # number of predictors
n_cols_train = predictors_train.shape[1]
n_cols_test = predictors_test.shape[1]

In [12]:
#Baseline model code starts here
#Import all the necessary libraries and packages
import keras

from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [13]:
# define regression model
import keras.backend as K

def mean_pred(predictors_test, target_test):
    return K.mean(target_test)

def std_pred(predictors_test, target_test):
    return K.std(target_test)

def regression_model():
    # create model - 10 nodes, relu activation function, 'adam' optimizer and 'mean_squared_error'
    #Note - data is not normalized
    model_train = Sequential()
    model_train.add(Dense(10, activation='relu', input_shape=(n_cols_train,)))
    model_train.add(Dense(10, activation='relu'))
    model_train.add(Dense(1))
    
    # compile model
    model_train.compile(optimizer='adam', loss='mean_squared_error',  metrics=[mean_pred, std_pred] )
    return model_train

In [14]:
# build the model
model_train = regression_model()

In [15]:
# fit the model - Requested 50 epochs - against test data with the mean, std and the mean squared error
#model_train.fit(predictors_train, target_train, validation_split=0.3, epochs=50, verbose=2)

model_train.fit(predictors_train, target_train, validation_data=(predictors_test,target_test), epochs=50, verbose=2)

Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 1s - loss: 2300.3353 - mean_pred: 43.5924 - std_pred: 25.9229 - val_loss: 969.7095 - val_mean_pred: 21.4668 - val_std_pred: 21.2141
Epoch 2/50
 - 0s - loss: 791.7111 - mean_pred: 38.4922 - std_pred: 20.6857 - val_loss: 524.0450 - val_mean_pred: 34.3554 - val_std_pred: 16.0116
Epoch 3/50
 - 0s - loss: 528.6056 - mean_pred: 33.7253 - std_pred: 16.2628 - val_loss: 388.7893 - val_mean_pred: 34.5337 - val_std_pred: 12.9669
Epoch 4/50
 - 0s - loss: 394.8006 - mean_pred: 36.0971 - std_pred: 13.5547 - val_loss: 310.4257 - val_mean_pred: 33.4327 - val_std_pred: 11.0696
Epoch 5/50
 - 0s - loss: 309.2805 - mean_pred: 35.6582 - std_pred: 11.6941 - val_loss: 252.0262 - val_mean_pred: 35.5742 - val_std_pred: 9.8610
Epoch 6/50
 - 0s - loss: 247.4437 - mean_pred: 35.8757 - std_pred: 10.4026 - val_loss: 209.7425 - val_mean_pred: 34.3425 - val_std_pred: 9.0672
Epoch 7/50
 - 0s - loss: 209.2866 - mean_pred: 35.9756 - std_pred: 9.9868 - val_loss: 181.4589 - val_mean_pred: 33.3148 - val_std_pred: 8.7760
Epoch 8/50
 - 0s - loss: 178.2954 - mean_pred: 36.4257 - std_pred: 9.7462 - val_loss: 161.9351 - val_mean_pred: 32.9807 - val_std_pred: 8.7786
Epoch 9/50
 - 0s - loss: 159.4772 - mean_pred: 36.1804 - std_pred: 9.6813 - val_loss: 146.2801 - val_mean_pred: 32.9410 - val_std_pred: 8.9550
Epoch 10/50
 - 0s - loss: 148.2784 - mean_pred: 35.8228 - std_pred: 9.8786 - val_loss: 138.6065 - val_mean_pred: 32.3792 - val_std_pred: 9.2259
Epoch 11/50
 - 0s - loss: 135.2153 - mean_pred: 35.7970 - std_pred: 10.2496 - val_loss: 123.8741 - val_mean_pred: 34.3769 - val_std_pred: 9.5181
Epoch 12/50
 - 0s - loss: 128.4695 - mean_pred: 35.8405 - std_pred: 10.4588 - val_loss: 117.2485 - val_mean_pred: 35.1797 - val_std_pred: 9.8425
Epoch 13/50
 - 0s - loss: 127.2588 - mean_pred: 36.1816 - std_pred: 10.8221 - val_loss: 113.3827 - val_mean_pred: 35.7228 - val_std_pred: 10.1233
Epoch 14/50
 - 0s - loss: 121.1363 - mean_pred: 36.2582 - std_pred: 10.9522 - val_loss: 109.7128 - val_mean_pred: 34.9874 - val_std_pred: 10.4044
Epoch 15/50
 - 0s - loss: 118.0457 - mean_pred: 36.2095 - std_pred: 11.3156 - val_loss: 110.3511 - val_mean_pred: 33.3004 - val_std_pred: 10.6323
Epoch 16/50
 - 0s - loss: 114.5228 - mean_pred: 36.5338 - std_pred: 11.5051 - val_loss: 104.8754 - val_mean_pred: 34.7318 - val_std_pred: 10.7980
Epoch 17/50
 - 1s - loss: 110.7964 - mean_pred: 36.1258 - std_pred: 11.6570 - val_loss: 105.0799 - val_mean_pred: 36.6143 - val_std_pred: 10.9738
Epoch 18/50
 - 0s - loss: 108.5395 - mean_pred: 35.9535 - std_pred: 11.9873 - val_loss: 101.3454 - val_mean_pred: 34.9939 - val_std_pred: 11.1405
Epoch 19/50
 - 0s - loss: 106.6099 - mean_pred: 36.1241 - std_pred: 11.9806 - val_loss: 100.9597 - val_mean_pred: 36.2767 - val_std_pred: 11.3063
Epoch 20/50
 - 0s - loss: 104.5464 - mean_pred: 36.6239 - std_pred: 12.1491 - val_loss: 99.8348 - val_mean_pred: 33.9772 - val_std_pred: 11.5279
Epoch 21/50
 - 0s - loss: 102.3998 - mean_pred: 35.9254 - std_pred: 12.3554 - val_loss: 98.0578 - val_mean_pred: 34.2467 - val_std_pred: 11.6609
Epoch 22/50
 - 0s - loss: 100.9554 - mean_pred: 36.0997 - std_pred: 12.4102 - val_loss: 98.2473 - val_mean_pred: 33.8045 - val_std_pred: 11.7547
Epoch 23/50
 - 0s - loss: 103.3194 - mean_pred: 36.4176 - std_pred: 12.5393 - val_loss: 95.9952 - val_mean_pred: 36.1235 - val_std_pred: 11.8720
Epoch 24/50
 - 0s - loss: 97.0211 - mean_pred: 36.1684 - std_pred: 12.6004 - val_loss: 94.4130 - val_mean_pred: 35.4484 - val_std_pred: 11.9842
Epoch 25/50
 - 0s - loss: 95.0460 - mean_pred: 36.0119 - std_pred: 12.7690 - val_loss: 93.7362 - val_mean_pred: 35.9012 - val_std_pred: 12.1243
Epoch 26/50
 - 0s - loss: 95.5714 - mean_pred: 36.4882 - std_pred: 12.8872 - val_loss: 92.4094 - val_mean_pred: 35.1412 - val_std_pred: 12.2333
Epoch 27/50
 - 0s - loss: 94.7663 - mean_pred: 35.7207 - std_pred: 12.9429 - val_loss: 91.1731 - val_mean_pred: 35.1873 - val_std_pred: 12.3382
Epoch 28/50
 - 0s - loss: 92.3147 - mean_pred: 36.6017 - std_pred: 13.0132 - val_loss: 90.2296 - val_mean_pred: 35.6445 - val_std_pred: 12.3520
Epoch 29/50
 - 0s - loss: 90.5416 - mean_pred: 36.2766 - std_pred: 12.9755 - val_loss: 94.7769 - val_mean_pred: 32.7015 - val_std_pred: 12.4482
Epoch 30/50
 - 0s - loss: 90.3001 - mean_pred: 35.6040 - std_pred: 13.0280 - val_loss: 87.2107 - val_mean_pred: 35.3133 - val_std_pred: 12.4934
Epoch 31/50
 - 0s - loss: 86.4569 - mean_pred: 36.4548 - std_pred: 13.2051 - val_loss: 86.3286 - val_mean_pred: 34.5557 - val_std_pred: 12.7058
Epoch 32/50
 - 0s - loss: 84.5468 - mean_pred: 36.2347 - std_pred: 13.3072 - val_loss: 85.8275 - val_mean_pred: 34.2901 - val_std_pred: 12.7151
Epoch 33/50
 - 0s - loss: 83.7243 - mean_pred: 35.9614 - std_pred: 13.3010 - val_loss: 83.8725 - val_mean_pred: 34.8992 - val_std_pred: 12.7663
Epoch 34/50
 - 0s - loss: 82.6599 - mean_pred: 36.3121 - std_pred: 13.4478 - val_loss: 87.0231 - val_mean_pred: 33.2704 - val_std_pred: 12.9307
Epoch 35/50
 - 0s - loss: 83.0647 - mean_pred: 35.8870 - std_pred: 13.4694 - val_loss: 82.5668 - val_mean_pred: 35.5999 - val_std_pred: 12.9202
Epoch 36/50
 - 0s - loss: 84.3384 - mean_pred: 36.5279 - std_pred: 13.4080 - val_loss: 88.2213 - val_mean_pred: 32.6639 - val_std_pred: 12.9882
Epoch 37/50
 - 0s - loss: 81.4735 - mean_pred: 36.1473 - std_pred: 13.5703 - val_loss: 81.5086 - val_mean_pred: 34.5495 - val_std_pred: 13.0482
Epoch 38/50
 - 0s - loss: 80.5719 - mean_pred: 35.8593 - std_pred: 13.6281 - val_loss: 84.2893 - val_mean_pred: 37.1411 - val_std_pred: 13.0334
Epoch 39/50
 - 0s - loss: 80.0701 - mean_pred: 36.3477 - std_pred: 13.6751 - val_loss: 80.3295 - val_mean_pred: 35.6003 - val_std_pred: 13.1532
Epoch 40/50
 - 0s - loss: 80.8525 - mean_pred: 36.1126 - std_pred: 13.5981 - val_loss: 81.1978 - val_mean_pred: 33.9208 - val_std_pred: 13.1651
Epoch 41/50
 - 0s - loss: 77.7810 - mean_pred: 36.2105 - std_pred: 13.7673 - val_loss: 80.5256 - val_mean_pred: 33.9623 - val_std_pred: 13.3152
Epoch 42/50
 - 0s - loss: 78.0879 - mean_pred: 36.0782 - std_pred: 13.8638 - val_loss: 79.0512 - val_mean_pred: 35.4910 - val_std_pred: 13.3116
Epoch 43/50
 - 0s - loss: 76.6416 - mean_pred: 36.2308 - std_pred: 13.8700 - val_loss: 88.5335 - val_mean_pred: 32.0032 - val_std_pred: 13.3751
Epoch 44/50
 - 0s - loss: 81.5242 - mean_pred: 36.1501 - std_pred: 13.9985 - val_loss: 78.4171 - val_mean_pred: 35.4588 - val_std_pred: 13.4456
Epoch 45/50
 - 0s - loss: 76.4958 - mean_pred: 35.9788 - std_pred: 13.9278 - val_loss: 83.8534 - val_mean_pred: 32.7115 - val_std_pred: 13.5498
Epoch 46/50
 - 0s - loss: 77.9472 - mean_pred: 36.4982 - std_pred: 13.9662 - val_loss: 77.9941 - val_mean_pred: 34.1669 - val_std_pred: 13.5261
Epoch 47/50
 - 0s - loss: 78.6513 - mean_pred: 35.8231 - std_pred: 14.0330 - val_loss: 76.8080 - val_mean_pred: 35.6639 - val_std_pred: 13.4628
Epoch 48/50
 - 0s - loss: 74.8786 - mean_pred: 36.1006 - std_pred: 13.8402 - val_loss: 76.9655 - val_mean_pred: 34.2286 - val_std_pred: 13.5140
Epoch 49/50
 - 0s - loss: 74.4313 - mean_pred: 36.0987 - std_pred: 14.0229 - val_loss: 77.5044 - val_mean_pred: 36.4157 - val_std_pred: 13.5436
Epoch 50/50
 - 0s - loss: 73.8739 - mean_pred: 36.4804 - std_pred: 14.0149 - val_loss: 80.9467 - val_mean_pred: 32.8078 - val_std_pred: 13.7141